# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a18c0f71cbf0de170b71c03b62e17fea6f399a796bc222287015644359fb6f0f543094825d7a83bffc9df0e7b211b704317f3fda3022cd9e41a9d6ae4476317f

test:
  secret_key_base: 6e4ee82a1c0ec928f6a5a2f2982c2bbc1a7d2af20cbddb9f01ccfb8fa3eb064463513fd5f2a53a36d35b6c7164c5874ff37d2795564a2e40267ff16db9db8055

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
